[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/02_softmax.ipynb)

# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.6 MB/s eta 0:00:00


In [2]:
import torch

In [32]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    x = x - torch.max(x, dim=dim, keepdim=True).values
    return torch.exp(x) / torch.sum(torch.exp(x), dim=dim, keepdim=True)

In [33]:
# 🧪 Debug
x = torch.tensor([1.0, 2.0, 3.0])
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

Output: tensor([0.0900, 0.2447, 0.6652])
Sum:    tensor(1.)
Ref:    tensor([0.0900, 0.2447, 0.6652])


In [34]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
  ✅ [1/3] Basic 1-D (1.6ms)
  ✅ [2/3] 2-D along dim=-1 (0.6ms)
  ✅ [3/3] Numerical stability (0.6ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (2.7ms total)
  Progress saved. Run status() to see your dashboard.



In [20]:
x = torch.randn(2, 3)
x

tensor([[-2.1852,  0.5380,  3.3752],
        [-0.3103, -0.2379, -0.7426]])

In [22]:
torch.max(x, dim=-1).values

tensor([ 3.3752, -0.2379])

In [24]:
x - torch.max(x, dim=-1, keepdim=True).values

tensor([[-5.5603, -2.8371,  0.0000],
        [-0.0724,  0.0000, -0.5047]])

In [25]:
torch.exp(x) / torch.sum(torch.exp(x), dim=-1, keepdim=True)

tensor([[0.0036, 0.0552, 0.9412],
        [0.3671, 0.3947, 0.2382]])