[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/16_cross_entropy.ipynb)

# 🟢 Easy: Cross-Entropy Loss

Implement **cross-entropy loss** from scratch.

$$\text{CE}(x, y) = -\log\frac{e^{x_y}}{\sum_j e^{x_j}}$$

### Signature
```python
def cross_entropy_loss(logits: Tensor, targets: Tensor) -> Tensor:
    # logits: (B, C) float, targets: (B,) long indices
    # Returns: scalar loss (mean over batch)
```

### Rules
- Do NOT use `F.cross_entropy` or `nn.CrossEntropyLoss`
- Must be numerically stable (use logsumexp trick)

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.6 MB/s eta 0:00:00


In [2]:
import torch

In [73]:
# ✏️ YOUR IMPLEMENTATION HERE

def cross_entropy_loss(logits, targets):
    logits = logits - torch.max(logits, dim=1, keepdim=True).values  #Subtract max from each row for numerical stability

    log_probs = logits - torch.log(torch.sum(torch.exp(logits), dim=1, keepdim=True))   #Calculate log_probs instead of usual probs
    relevant_log_probs = log_probs[range(len(log_probs)), targets]

    loss = -torch.mean(relevant_log_probs)
    return loss


In [74]:
# 🧪 Debug
logits = torch.randn(4, 10)
targets = torch.randint(0, 10, (4,))
print('Loss:', cross_entropy_loss(logits, targets))
print('Ref: ', torch.nn.functional.cross_entropy(logits, targets))

Loss: tensor(2.6524)
Ref:  tensor(2.6524)


In [75]:
# ✅ SUBMIT
from torch_judge import check
check('cross_entropy')


🧪 Testing: Cross-Entropy Loss (Easy)
──────────────────────────────────────────────────
  ✅ [1/4] Matches F.cross_entropy (3.4ms)
  ✅ [2/4] Numerical stability (0.9ms)
  ✅ [3/4] Scalar output (0.5ms)
  ✅ [4/4] Gradient flow (1.2ms)
──────────────────────────────────────────────────
  🎉 All 4 tests passed! (6.0ms total)
  Progress saved. Run status() to see your dashboard.



In [68]:
logits = torch.randn(4, 10)
targets = torch.randint(0, 10, (4,))

logits.shape, targets.shape

(torch.Size([4, 10]), torch.Size([4]))

In [69]:
logits

tensor([[ 0.1102, -0.8188,  0.6328, -1.9169, -0.5596,  0.5335,  0.4069,  0.3946,
          0.4147, -1.5090],
        [ 2.0360,  0.1316, -0.0744, -1.0922,  0.3920,  0.5945, -0.6334, -1.4677,
         -0.8785, -2.0784],
        [ 1.1711,  0.0975,  0.9634,  0.8403, -0.1448,  0.6376, -0.2813, -1.3299,
         -0.6538,  1.7198],
        [-0.9610, -0.6375, -0.8870,  0.8388,  1.1529, -1.7611, -1.1070, -1.7174,
          1.5346, -0.0032]])

In [70]:
torch.exp(logits) / torch.sum(torch.exp(logits), dim=1, keepdim=True)

tensor([[0.1055, 0.0417, 0.1779, 0.0139, 0.0540, 0.1611, 0.1419, 0.1402, 0.1430,
         0.0209],
        [0.5226, 0.0778, 0.0633, 0.0229, 0.1010, 0.1236, 0.0362, 0.0157, 0.0283,
         0.0085],
        [0.1685, 0.0576, 0.1369, 0.1210, 0.0452, 0.0988, 0.0394, 0.0138, 0.0272,
         0.2916],
        [0.0292, 0.0403, 0.0314, 0.1763, 0.2414, 0.0131, 0.0252, 0.0137, 0.3536,
         0.0760]])

In [71]:
probs = torch.exp(logits - torch.log(torch.sum(torch.exp(logits), dim=1, keepdim=True)))
probs

tensor([[0.1055, 0.0417, 0.1779, 0.0139, 0.0540, 0.1611, 0.1419, 0.1402, 0.1430,
         0.0209],
        [0.5226, 0.0778, 0.0633, 0.0229, 0.1010, 0.1236, 0.0362, 0.0157, 0.0283,
         0.0085],
        [0.1685, 0.0576, 0.1369, 0.1210, 0.0452, 0.0988, 0.0394, 0.0138, 0.0272,
         0.2916],
        [0.0292, 0.0403, 0.0314, 0.1763, 0.2414, 0.0131, 0.0252, 0.0137, 0.3536,
         0.0760]])

In [72]:
targets

tensor([5, 5, 3, 6])

In [39]:
probs[range(probs.shape[0]), targets]

tensor([0.1611, 0.1236, 0.1210, 0.0252])